### ISSUE TITLE
Security vulnerability with strip-ansi dependency

### ISSUE THREAD

**Issue by akaraman85** [shannonmoeller/cli-columns#4]
Currently strip-ansi@^3.0.1 has a dependency on a vulnerable version of ansi-regex.  The vulnerability is only fixed in ansi-regex >6.0.0, https://github.com/chalk/ansi-regex/releases/tag/v6.0.1

Additionally string-width depends on a version of strip-ansi that is vulnerable.

Vulnerability link - https://snyk.io/vuln/npm:ansi-regex

**Comment by shannonmoeller** [comment]
Thank you! Updated dependencies and released as [v4.0.0](https://github.com/shannonmoeller/cli-columns/releases/tag/v4.0.0). Used [`ansi-regex@5.0.1`](https://github.com/chalk/ansi-regex/releases/tag/v5.0.1) which backported the fix to the version that maintains CSM support.

**Comment by akaraman85** [comment]
Thank you!
